/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as HotseatRouteImport } from './routes/hotseat'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as GargalosRouteImport } from './routes/gargalos'
import { Route as FaturamentoRouteImport } from './routes/faturamento'
import { Route as ExportarRouteImport } from './routes/exportar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotseatIdRouteImport } from './routes/hotseat.$id'

const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const HotseatRoute = HotseatRouteImport.update({
  id: '/hotseat',
  path: '/hotseat',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const GargalosRoute = GargalosRouteImport.update({
  id: '/gargalos',
  path: '/gargalos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturamentoRoute = FaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportarRoute = ExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotseatIdRoute = HotseatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HotseatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/exportar': typeof ExportarRoute
  '/faturamento': typeof FaturamentoRoute
  '/gargalos': typeof GargalosRoute
  '/grupos': typeof GruposRoute
  '/historico': typeof HistoricoRoute
  '/hotseat': typeof HotseatRouteWithChildren
  '/membros': typeof MembrosRoute
  '/hotseat/$id': typeof HotseatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/exportar': typeof ExportarRoute
  '/faturamento': typeof FaturamentoRoute
  '/gargalos': typeof GargalosRoute
  '/grupos': typeof GruposRoute
  '/historico': typeof HistoricoRoute
  '/hotseat': typeof HotseatRouteWithChildren
  '/membros': typeof MembrosRoute
  '/hotseat/$id': typeof HotseatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/exportar': typeof ExportarRoute
  '/faturamento': typeof FaturamentoRoute
  '/gargalos': typeof GargalosRoute
  '/grupos': typeof GruposRoute
  '/historico': typeof HistoricoRoute
  '/hotseat': typeof HotseatRouteWithChildren
  '/membros': typeof MembrosRoute
  '/hotseat/$id': typeof HotseatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/exportar'
    | '/faturamento'
    | '/gargalos'
    | '/grupos'
    | '/historico'
    | '/hotseat'
    | '/membros'
    | '/hotseat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/exportar'
    | '/faturamento'
    | '/gargalos'
    | '/grupos'
    | '/historico'
    | '/hotseat'
    | '/membros'
    | '/hotseat/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/exportar'
    | '/faturamento'
    | '/gargalos'
    | '/grupos'
    | '/historico'
    | '/hotseat'
    | '/membros'
    | '/hotseat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExportarRoute: typeof ExportarRoute
  FaturamentoRoute: typeof FaturamentoRoute
  GargalosRoute: typeof GargalosRoute
  GruposRoute: typeof GruposRoute
  HistoricoRoute: typeof HistoricoRoute
  HotseatRoute: typeof HotseatRouteWithChildren
  MembrosRoute: typeof MembrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotseat': {
      id: '/hotseat'
      path: '/hotseat'
      fullPath: '/hotseat'
      preLoaderRoute: typeof HotseatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gargalos': {
      id: '/gargalos'
      path: '/gargalos'
      fullPath: '/gargalos'
      preLoaderRoute: typeof GargalosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturamento': {
      id: '/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof FaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportar': {
      id: '/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof ExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotseat/$id': {
      id: '/hotseat/$id'
      path: '/$id'
      fullPath: '/hotseat/$id'
      preLoaderRoute: typeof HotseatIdRouteImport
      parentRoute: typeof HotseatRoute
    }
  }
}

interface HotseatRouteChildren {
  HotseatIdRoute: typeof HotseatIdRoute
}

const HotseatRouteChildren: HotseatRouteChildren = {
  HotseatIdRoute: HotseatIdRoute,
}

const HotseatRouteWithChildren =
  HotseatRoute._addFileChildren(HotseatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExportarRoute: ExportarRoute,
  FaturamentoRoute: FaturamentoRoute,
  GargalosRoute: GargalosRoute,
  GruposRoute: GruposRoute,
  HistoricoRoute: HistoricoRoute,
  HotseatRoute: HotseatRouteWithChildren,
  MembrosRoute: MembrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
